# Generated by Django 5.2.2 on 2025-06-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plates',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plates',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
