# Generated by Django 5.2.2 on 2025-06-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0002_alter_plates_created_at_alter_plates_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='plates',
            name='categoies',
            field=models.ManyToManyField(blank=True, related_name='plates', to='categories.category'),
        ),
    ]
