# Generated by Django 5.2.2 on 2025-06-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0003_plates_categoies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plates',
            name='categoies',
        ),
        migrations.AddField(
            model_name='plates',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='plates', to='categories.category'),
        ),
    ]
