# Generated by Django 5.2.2 on 2025-06-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Company')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('image', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='Image')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.IntegerField(verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
            },
        ),
    ]
